### ISSUE TITLE
tcafeaa rules

### ISSUE THREAD

**Issue by gtgvxinf** [yous/YousList#14]
tcafeaa.com has now moved to tcafeh.com. Can you add similar rules for tcafeh.com?

tcafeh.com###cssImg > TBODY > TR:last-child > TD:first-child > TABLE:last-child
tcafeh.com###cssImg > TBODY > TR:last-child > TD:first-child > TABLE:first-child > TBODY > TR:last-child
tcafeh.com###mw_basic > TABLE:nth-child(6) > TBODY > TR:last-child > TD > TABLE > TBODY > TR > TD:first-child
tcafeh.com###mw_basic > CENTER:nth-child(2)
tcafeh.com###cssImg > TBODY > TR:first-child > TD:last-child > TABLE > TBODY > TR > TD > TABLE > TBODY > TR > TD.dp:last-child
tcafeh.com###divpop

Maybe rules for old domain tcafeaa.com can be removed.

**Comment by Fenslett** [comment]
The characteristics of websites whose own name is constantly changing to avoid being banned by National Police Agency are that they have their image server for advertisements.
On analysis, most advertisements on the site that start with **tcafe** are stored and provided in a URL form on **imgtong.com**, which means the majority involved with them can be blocked by using this:
```
||imgtong.com
```
But, there is a side effect all images are hidden. so I looked into DOM elements on the site, made a bunch of exception rules requiring at least user can use the site 

```
@@img.imgtong.com/count_bg.gif
@@img.imgtong.com/count_bg._shodow.gif
@@img.imgtong.com/btn_*.gif
@@img.imgtong.com/cbr.gif
@@img.imgtong.com/*image*.gif
@@img.imgtong.com/bg_sign.gif
@@img.imgtong.com/coin.fig
@@img.imgtong.com/comm.png
@@img.imgtong.com/ut.gif
@@img.imgtong.com/fu.png
@@img.imgtong.com/q.png
@@img.imgtong.com/_start.png
@@img.imgtong.com/_stop.png
@@img.imgtong.com/pup.gif
@@img.imgtong.com/pdown.gif
@@img.imgtong.com/nogap.gif
||imgtong.com
```

I tested it out on *tcafeh.com*, *tcafeaa*.com and *tcafegg.com*. 
Occasionally, some miscellaneous images like level icons are not shown correctly, but I think it wouldn't hurt any users to use the site.

**Comment by yous** [comment]
@Fenslett Thanks for the suggestion. But I'm worried about the case that we block non-ad images of imgtong.com, referred by domains not owned by Tcafe. I don't want to introduce false positive ad-blocking since we _may_ accept some ads but we _won't_ accept blocking real contents by ad-blocker. I may disable that ad-blocker immediately if it blocks contents that I want to see.

So, I found a Twitter account of Tcafe, https://twitter.com/tcafenet, and I'll add all of them that are accessible now. This is the list of domains:

- tcafe.net
- tcafeaa.com
- tcafeby.com
- tcafegg.com
- tcafego.com
- tcafeh.com
- tcafek.com
- tcafen.com
- tcafeon.com
- tcafex.com
- tcafez.net

Also, as I think, users usually access tcafe.net, and other domains are just temporal ones. Here we handle tcafe.net, so the case when users access another site and see ads may less often.

**Comment by Fenslett** [comment]
@yous Yes. I understand what you're concerned about.
The reason I made a suggestion that blocks some image stored on *imgtong.com* was the owner *imgtong.com* and a series of *tcafe* site are completely the same and we could save unnecessary data traffic by blocking them. According to the introduction of Adblock website, *DOM elements* become hidden only, not blocked. It means our browser always send a website the requests for advertisement image. I thought this mechanism was a waste of money to send, resend, process them. :+1: 

Thanks for your reply by the way.

**Comment by yous** [comment]
@Fenslett Ah, didn't know that the owner of Tcafe also owns imgtong.com. Also thank you for the notice about DOM elements. If we can block some obvious ad images, I'll add them.
