### ISSUE TITLE
localhost options

### ISSUE THREAD

**Issue by SainteCelery** [yous/YousList#31]
Any chance we could get a 0.0.0.0 version of the host.txt?

**Comment by yous** [comment]
Hi, can I ask the reasons you use 0.0.0.0? I may change the hosts.txt to use 0.0.0.0 instead of 127.0.0.1, but I wasn't able to find any special reason. It would be helpful if you provide me some use cases. Are you running a web server on your own machine?

**Comment by SainteCelery** [comment]
Hi. 0.0.0.0, as a road to nowhere, technically resolves more quickly than 127. Whether the difference is enough to be reliably perceived, I'll admit, I don't know. But I've been using it for my hosts lists for the last several years for that reason. I am not running a server at the moment, but I have and have been procrastinating setting up a caching server. If it's a hassle, no worries; it'd just be nice to automatically grab your list without having to edit it before using it.

**Comment by yous** [comment]
I've been looking for technical advantages of using 0.0.0.0 instead of 127.0.0.1, but it seems to depend on the implementation. Using 0.0.0.0 may be slightly quicker than 127.0.0.1, or just equivalent to it.

Here are some threads, just for the history.
- http://www.dslreports.com/forum/r24621780-hosts-127-0-0-1-vs-0-0-0-0
- http://www.dslreports.com/forum/r16790135-Large-Hosts-file-0-0-0-0-or-127-0-0-1

[AdAway](https://github.com/AdAway/AdAway) is an open source ad blocker for Android using the hosts file, and they parse 127.0.0.1 and 0.0.0.0 to equivalent rules. Also their [default sources](https://github.com/AdAway/AdAway/wiki/HostsSources#adaways-default-hosts-sources) are using 127.0.0.1.

I found that [MVPS HOSTS](http://winhelp2002.mvps.org/hosts.htm) changed 127.0.0.1 to 0.0.0.0 because of a slowdown issue in Windows 8.1.

So, I'll change to 0.0.0.0. There are some cases that 127.0.0.1 causes issues like a slowdown noted by MVPS, and when running a web server on localhost. If someone experiences an issue with 0.0.0.0, I'll think again at that time.
